### ISSUE TITLE
React Warning -manually calling a React.PropTypes 

### ISSUE THREAD

**Issue by tarr11** [rainforestapp/react-pusher#5]
```
Warning: You are manually calling a React.PropTypes validation function for the `channel` prop on `t`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
```

**Comment by juliankrispel** [comment]
thanks @tarr11 will update shortly

**Comment by FranckErnewein** [comment]
this was fixed was fixed by https://github.com/rainforestapp/react-pusher/commit/4450df7cb3ec80af2d4a956245e8ffca8684a14b
but not published on npm :(

**Comment by etiennejcharles** [comment]
@juliankrispel : When will this be pushlished ? Still getting that warning

**Comment by juliankrispel** [comment]
I don't have access to this anymore - maybe @prayogoa  or @ziahamza can publish this :)

**Comment by prayogoa** [comment]
Sorry for the delay, we'll publish an update soon!
